### PR TITLE
Add comment to stocktake

### PR DESCRIPTION
**Pull request by andreievg**
Can add comment and edit name in stocktake edit page

### CODE REVIEW

**Comment by andreievg** [comment]
screen shot 2017-11-23 at 12 30 57 pm

**Comment by andreievg** [comment]
Tested:
* Changing name with manage stocktake updates name in the info component (topLeftComponent)
* Changing name / comment in modal changes name / comment in database
* Can't change name / comment in finalised stocktake
* Comment / Name resync successfully

**Comment by andreievg** [comment]
@Chris-Petty as per individual comment per line, will have to add comment field to stock_take_lines in mSupply database

**Comment by Chris-Petty** [comment]
In my own comment... I thought there already was, must be for transaction or requisition lines. Line by line here probably not necessary, probably why it doesn't exist!

**Pull request merged**
