### PR TITLE
#624 Keyboard pop up issue on input fields fixed

### LINKED ISSUE #624: Keyboard pops up then disappears when selecting field
Build Number: 2.1.0-rc8

Description:
When editing a stocktake it can be frustrating when selecting a field to have the keyboard briefly come up and immediately dismiss.

Reproducible: Yes, usually

Reproduction Steps:

1. Make a stocktake with 20+ items
2. Tap the editable quantity field of the item at the very bottom of screen
3. You enter a number and tap "Next" on device keyboard
4. Cursor advances to next cell, but keyboard closes
5. Tap on the cell: the keyboard opens and immediately closes again.
6. Tap again on the cell and now the keyboard stays open and you can enter the next value. Ick.

### PR DESCRIPTION
**Pull request by arjunSussol**
fixes #624 

"react-native-keyboard-aware-scroll-view" integrated to fix this issue.

Keyboard could not appropriately pop up on input fields when selecting last fields on table.
Also, keyboard cover the input fields on initial page and login form.

Might be due to Modal used in Login form, this issue didn't fix.

Due to eslint and prettier setting to my VS, there are some auto tidy up

@Chris-Petty same fix applied to table also as it looks fine.

### CODE REVIEW

**Comment by craigdrown** [comment]
@Chris-Petty I was just about to make an issue and saw this which may or may not fix what I'm seeing:

1. In a list view (say entering quantities in a customer invoice
2. You enter a number and tap "Next"
3. Cursor advances to next cell, but keyboard closes
4. Tap on the cell: the keyboard opens and immediately closes again.
5. Tap again on the cell and now the keyboard stays open and you can enter the next value. Ick.

**Comment by Chris-Petty** [comment]
@craigdrown https://github.com/sussol/mobile/issues/624 should have been linked. I'm stealing your description.

**Comment by arjunSussol** [comment]
@Chris-Petty I have also tested this issue with tablet via USB connection.
Seems to be fine. Also, I hoping that this could fix the another issue: https://github.com/sussol/mobile/issues/625

Please, review this and let me know if you need further improvements.
After this I am planning to jump to another bug fixing.

**Comment by andreievg** [comment]
Hi @arjunSussol -> good find `react-native-keyboard-aware-scroll-view`.

I've testing this PR, it looks like the issues are addressed but the whole page is movable now.

You can keep the code that deals with login pages, but not the wrappers around generic pages.

So will probably need to make an issue just for the login page keyboard fix, and link that issue to this PR.

I've added comment in the #624 issue suggesting a fix.

**Comment by andreievg** [comment]
As per prettier/eslint changes, there is an issue to 'standardise' prettier/eslint formatting. Hopefully this will be done soon, until then prettier changes are a nuisance when reviewing PR, so you should disable prettier in vscode (or whatever editor you are using).

It maybe easier to close this PR and start a new one

**Comment by arjunSussol** [comment]
@Chris-Petty and @andreievg as this PR is no more needed I am closing this.

**Pull request closed without merging**
