### PR TITLE
Tl translation update

### PR DESCRIPTION
**Pull request by nmadruga**
Branched from #440 
- Update Strings translation for Timor Leste
- Create new String entries for Timor Leste

### CODE REVIEW

**Comment by Chris-Petty** [comment]
@DhanyaHerath if you're looking to test something, just trawling through everywhere and making sure the strings actually fit for the Tetum would be good. Column headers particularly.

If you're real keen, you can make the adjustments yourself and make a commit. It's just a tedious act of slipping `\n` new line characters in the strings where ever needed.

**Comment by edmofro** [comment]
Hey team especially @nmadruga, added one more string that needs a translation: search_for_the_supplier
We also need these translations for Kiribati at some point.

**Comment by nmadruga** [comment]
@edmofro I added an issue to make the translation for Kiribati. And will send an e-mail to Alex to get the translation for search_for_the_supplier. @andreievg and @Chris-Petty are we going to add any other line that I should ask him for the translation now?

**Comment by edmofro** [comment]
Sounds good @nmadruga. Might be a good idea to send existing translation for search_for_the_customer so that the search_for_the_supplier translation is consistently worded.

**Comment by nmadruga** [comment]
Read for merge

**Comment by edmofro** [comment]
@nmadruga resolved conflicts on this, but there have been a few TODO added for tl...it's never ending! Can you follow up?

**Comment by nmadruga** [comment]
@andreievg @Chris-Petty could you find out with Alex and Agusto the translations for the new lines, please? I think it would be more straight-forward than me sending an e-mail to them now.

**Comment by andreievg** [comment]
Update from master will be very messy, as there have been additions, removals and changes to strings, we have to decide for the future, either:
* Translation branch is the last branch to be created before release, and everyone fixes localisation conflicts in their own PR's
* Running translation branch is updated from master after every PR merge, by the owner of PR
* A script that turns existing localisation files into one big spreadsheet, and a script that does the reverse (https://github.com/sussol/mobile/issues/484) 

I am for the third option, but since time does not allow, we'll go with option one. Since there have been so many changes to localisation strings, new PR will be created from master and I will manually add all of existing TL translations based on `// TODO` strings, and we'll get Augusto to update remaining TL strings before Monday release

**Comment by Chris-Petty** [comment]
Agree with @andreievg

**Comment by Chris-Petty** [comment]
4th option better, I've merged master into this, I've rebased #485 to merge into this PRs branch. Once @andreievg resolves the conflicts in his branch (largely accepting the to date strings from this PR that weren't outright removed by his PR).

Once Andrei's is merged, this branch is good to go.

**Pull request merged**
