### PR TITLE
#408 Stock Item usage lookup

### PR DESCRIPTION
**Pull request by andreievg**
* Monthly Usage in stock page
* Batch information in stock page

### CODE REVIEW

**Comment by andreievg** [comment]
screen shot 2017-09-11 at 3 57 25 pm

**Comment by andreievg** [comment]
it seems like inconsistencies in font's character length
screen shot 2017-09-12 at 5 08 40 pm

**Comment by andreievg** [comment]
So going with a comma and two spaces as per:
screen shot 2017-09-12 at 5 18 55 pm

**Comment by GaryWilletts** [comment]
I realise I'm late to the party (didn't see stuff happening on Balsamiq etc) but the batch stuff seems really wordy. Why not have Batch: _batch name_, Expiry: _expiry date_, Quantity: _quantity_ i.e. ditch the name part. Just confusing and takes up extra screen space I think.

**Comment by andreievg** [comment]
@GaryWilletts, I updated as per your suggestion, yes it does make it easier on the eye, thanks. And there was nothing on Balsamiq for this (there was an issue to include monthly usage in the expansion summary, and while implementing that we also implemented showing batch info, was quite easy).

Below is the new view (three batches, one with full info, next one with no name, and third one with no name or expiry):

screen shot 2017-09-28 at 2 14 31 pm

**Comment by GaryWilletts** [comment]
Nice. Would be awesomer if you treated the 3 values as columns (fixed width divs?) so they all lined up (much quicker to read at a glance). Then you could put a "-" when there's no value. Gotta be a sinch for a chap of your talents ;-)

**Comment by andreievg** [comment]
Thank you Gary.

In the StockPage Expansion component is used with PageInfo component (both written prior to may with mobile), there is a limit to what can be displayed with PageInfo (atm only text, editable text and 'selectable'). Since this PR focused on a low priority issue, and actually the batch info display wasn't even a part of that issue, I didn't really want to spend excessive time modifying (or replacing) PageInfo component to handle 'custom' columns and create another custom table <- as we like to create everything generic/reusable (which will be a sinch, but +time +complexity +100+ extra lines..).  I did try to align batch info columns with via text (tab, spaces) but in the font we use, character widths are inconsistent.

Given the importance and priority of the feature (low, low), simplicity of implementation (currently quite simple) and again simplicity of interface (only show what needs to be shown).. taking into account those three -> We should keep this change and this PR minimalistic (as is :)

**Pull request merged**
